"""Image tiers: turn a clean PDF into a scan, phone photo, photocopy/fax, screen photo or screenshot.

Design follows three principles from PureDocBench (arXiv:2605.07492, the benchmark introduced by the
WeVisDoc paper):

1. **Aligned views share one ground truth.** The same source document is rendered into Clean, Digital
   Degraded and Real Degraded views with a single annotation -- degradation changes pixels, not content.
   So every scene here starts from the same PDF, keeps the manifest's printed and semantic truth as is,
   and only adds `tier` / `scene` / `severity` / `ops`.
2. **A scene is a chain of operators, not a single one.** PureDocBench's ten digital-degradation scenes
   (aged_archive, book_binding, multi_gen_copy, fax_thermal, low_quality_print, ink_bleed,
   heavy_compression, uneven_lighting, geometric_distort, noise_blur_combo) are each a fixed operator
   combination drawn from four stages -- paper, print/copy, capture, digital processing -- scaled by one
   0-1 severity (mild 0.3 / moderate 0.6 / severe 0.9). Its real capture chains are four: phone photo of
   paper (flat/creased/bent/under a cover x normal/low light/flash x top-down/oblique), phone photo of a
   photocopy, phone photo of a screen, and a screenshot forwarded through chat compression. Our scenes
   follow those two tables and are named by this repo's tiers: T2 scan, T3 phone photo, T4 degraded
   document, T6 screenshot/screen photo.
3. **A view where content is unreadable keeps no source truth.** PureDocBench's training rule keeps the
   source annotation only while every supervised item stays visible and legible, otherwise it rejects the
   sample or crops the annotation to what remains visible. Here every scene keeps the whole page in frame
   (top-down shot, long screenshot, full-page scan); the severe tier goes into the `stress` bucket, not
   the main leaderboard, and per-line readability is reported by `audit/readability.py` via OCR, scene by
   scene -- a report, not a gate, since OCR missing a line doesn't mean a human would.

Depends only on PIL and numpy (PureDocBench's own implementation uses OpenCV; this repo avoids that
dependency for one layer). Deterministic: every random draw comes from `RandomState(sha1(doc_id + scene))`,
byte-identical for a given seed.

Every output image carries a synthetic mark -- JPEG's EXIF ImageDescription/Software, PNG's text chunk --
a second control, beyond the banner, for the "mistaken as real" risk in docs/zh-CN/plan.md §4.1(d).
"""

from __future__ import annotations

import hashlib
import io
import math

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, PngImagePlugin

SYNTHETIC_MARK = "SYNTHETIC SAMPLE - generated by mirobody-gen, not a real patient record"

#: scene -> (tier, description, stages). Stages are an ordered list of (op name, parameter sampler); a
#: sampler takes (rng, severity) and returns that op's parameter dict. Parameters are logged to the
#: manifest's `ops`, so how each image was produced is always traceable.
SCENES: dict[str, dict] = {}


def _scene(name: str, tier: str, description: str, real_chain: str, stages: list) -> None:
    SCENES[name] = {"tier": tier, "description": description, "real_chain": real_chain, "stages": stages}


# ── Basic helpers ─────────────────────────────────────────────────
def _to_np(img: Image.Image) -> np.ndarray:
    return np.asarray(img.convert("RGB"), dtype=np.float32)


def _to_img(arr: np.ndarray) -> Image.Image:
    return Image.fromarray(np.clip(arr, 0, 255).astype(np.uint8), "RGB")


def _paper(arr: np.ndarray) -> tuple[float, float, float]:
    """Paper colour: the median of the image's four corners, used to fill blanks left by rotation or
    perspective instead of plain black."""
    h, w = arr.shape[:2]
    m = max(4, min(h, w) // 40)
    corners = np.concatenate([arr[:m, :m].reshape(-1, 3), arr[:m, -m:].reshape(-1, 3),
                              arr[-m:, :m].reshape(-1, 3), arr[-m:, -m:].reshape(-1, 3)])
    med = np.median(corners, axis=0)
    return float(med[0]), float(med[1]), float(med[2])


def _gray(arr: np.ndarray) -> np.ndarray:
    return arr[..., 0] * 0.299 + arr[..., 1] * 0.587 + arr[..., 2] * 0.114


def _blur(arr: np.ndarray, radius: float) -> np.ndarray:
    if radius <= 0:
        return arr
    return _to_np(_to_img(arr).filter(ImageFilter.GaussianBlur(radius)))


def _lowfreq_noise(rng: np.random.RandomState, h: int, w: int, sigma: float, radius: float) -> np.ndarray:
    small = rng.normal(0, sigma, (max(2, h // 8), max(2, w // 8))).astype(np.float32)
    img = Image.fromarray(np.clip(small + 128, 0, 255).astype(np.uint8), "L").resize((w, h), Image.BILINEAR)
    if radius:
        img = img.filter(ImageFilter.GaussianBlur(radius))
    return np.asarray(img, dtype=np.float32) - 128


# ── Operators: paper ──────────────────────────────────────────────
def paper_texture(arr, rng, strength=0.3, **_):
    h, w = arr.shape[:2]
    noise = _lowfreq_noise(rng, h, w, 8 * strength, 1.0)
    return arr + noise[..., None]


def yellowing(arr, rng, strength=0.5, **_):
    overlay = np.array([240, 220, 170], dtype=np.float32)      # warm yellow (RGB)
    alpha = 0.08 * strength
    out = arr * (1 - alpha) + overlay * alpha
    return out * (1.0 - 0.15 * strength) + 10 * strength


def fade_ink(arr, rng, strength=0.5, **_):
    alpha = 0.3 * strength
    return arr * (1 - alpha) + 200 * alpha


def foxing_spots(arr, rng, strength=0.5, **_):
    img = _to_img(arr)
    overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    h, w = arr.shape[:2]
    for _ in range(int(30 * strength)):
        cx, cy = int(rng.randint(0, w)), int(rng.randint(0, h))
        r = int(rng.randint(3, int(8 + 10 * strength) + 1))
        color = (int(rng.randint(150, 200)), int(rng.randint(100, 150)), int(rng.randint(60, 100)),
                 int(rng.randint(60, 140)))
        draw.ellipse((cx - r, cy - r, cx + r, cy + r), fill=color)
    overlay = overlay.filter(ImageFilter.GaussianBlur(1.5))
    img = Image.alpha_composite(img.convert("RGBA"), overlay).convert("RGB")
    return _to_np(img)


def stains(arr, rng, strength=0.5, count=None, **_):
    img = _to_img(arr)
    overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    h, w = arr.shape[:2]
    n = count if count is not None else int(rng.randint(1, 4))
    for _ in range(n):
        cx, cy = int(rng.randint(0, w)), int(rng.randint(0, h))
        rx, ry = int(rng.randint(w // 20, w // 6)), int(rng.randint(h // 30, h // 8))
        palette = [(200, 170, 90), (150, 120, 80), (120, 120, 120), (190, 150, 140)]
        color = palette[int(rng.randint(0, len(palette)))]
        draw.ellipse((cx - rx, cy - ry, cx + rx, cy + ry), fill=(*color, int(40 + 60 * strength)))
    overlay = overlay.filter(ImageFilter.GaussianBlur(max(2.0, w / 120)))
    img = Image.alpha_composite(img.convert("RGBA"), overlay).convert("RGB")
    return _to_np(img)


def fold_lines(arr, rng, strength=0.5, lines=None, **_):
    """A crease: a dark band next to a light one (paper catching light along the fold), horizontal or
    vertical, with a slight tilt."""
    h, w = arr.shape[:2]
    out = arr.copy()
    n = lines if lines is not None else int(rng.randint(1, 3))
    Y, X = np.mgrid[0:h, 0:w].astype(np.float32)
    for _ in range(n):
        horizontal = rng.rand() < 0.6
        pos = rng.uniform(0.25, 0.75)
        tilt = rng.uniform(-0.03, 0.03)
        if horizontal:
            d = Y - (pos * h + tilt * (X - w / 2))
        else:
            d = X - (pos * w + tilt * (Y - h / 2))
        width = max(2.0, min(h, w) / 250)
        dark = np.exp(-(d / (width * 2)) ** 2) * (60 * strength)
        light = np.exp(-((d - width * 2.5) / width) ** 2) * (25 * strength)
        out = out - dark[..., None] + light[..., None]
    return out


def page_curl(arr, rng, strength=0.5, **_):
    """A bend, not flattened out: content near one side shifts by a sine curve, with a gradient shadow."""
    h, w = arr.shape[:2]
    amp = int(12 * strength)
    if amp <= 0:
        return arr
    side = rng.choice([-1, 1])
    cols = np.arange(w, dtype=np.float32)
    t = cols / w if side > 0 else 1 - cols / w
    shift = amp * np.sin(np.pi * t) * (1 - t)
    out = np.empty_like(arr)
    rows = np.arange(h, dtype=np.float32)
    for x in range(w):
        src = np.clip(rows + shift[x], 0, h - 1)
        lo = np.floor(src).astype(int)
        hi = np.minimum(lo + 1, h - 1)
        frac = (src - lo)[:, None]
        out[:, x] = arr[lo, x] * (1 - frac) + arr[hi, x] * frac
    shade = 1.0 - 0.35 * strength * np.exp(-((t - 0.0) / 0.25) ** 2)
    return out * shade[None, :, None]


# ── Operators: print / copy / fax ────────────────────────────────────
def ink_bleed(arr, rng, strength=0.5, **_):
    g = _gray(arr)
    mask = (g < 180).astype(np.float32) * 255
    k = int(3 + 2 * strength) | 1
    dil = np.asarray(Image.fromarray(mask.astype(np.uint8), "L").filter(ImageFilter.MaxFilter(k)), dtype=np.float32)
    dil = _blur(np.repeat(dil[..., None], 3, axis=2), 1.5)[..., 0]
    blend = dil / 255 * 0.4 * strength
    return arr * (1 - blend[..., None]) + 50 * blend[..., None]


def toner_banding(arr, rng, strength=0.5, **_):
    h, w = arr.shape[:2]
    out = arr.copy()
    period = int(30 + 50 * (1 - strength))
    for y in range(0, h, period):
        band = min(int(period * 0.3), h - y)
        out[y:y + band] *= rng.uniform(0.85, 0.95)
    for _ in range(int(5 + 10 * strength)):
        y0 = int(rng.randint(0, h)); y1 = min(y0 + int(rng.randint(20, 60)), h)
        x0 = int(rng.randint(0, w)); x1 = min(x0 + int(rng.randint(2, 6)), w)
        out[y0:y1, x0:x1] *= 0.7
    return out


def copy_contrast(arr, rng, strength=0.5, **_):
    return arr * (1.0 + 0.5 * strength) - 30 * strength


def generation_loss(arr, rng, strength=0.5, **_):
    out = arr
    for _ in range(int(2 + 3 * strength)):
        out = _blur(out, 0.8)
        out = out + rng.normal(0, 3, out.shape).astype(np.float32)
        out = out * 1.05 - 5
    return out


def dirty_drum(arr, rng, strength=0.5, **_):
    h, w = arr.shape[:2]
    out = arr.copy()
    for _ in range(int(3 + 5 * strength)):
        x = int(rng.randint(0, w)); t = int(rng.randint(1, 3))
        a = rng.uniform(0.05, 0.15) * strength
        out[:, x:x + t] = out[:, x:x + t] * (1 - a) + 100 * a
    return out


def thermal(arr, rng, strength=0.5, **_):
    g = _gray(arr) * (1.5 + strength) - 60 * strength
    h, w = g.shape
    for _ in range(int(10 + 20 * strength)):
        y = int(rng.randint(0, h))
        g[y:y + 1] += rng.randint(-40, 40)
    g = np.clip(g, 0, 255)
    out = np.repeat(g[..., None], 3, axis=2)
    tint = np.array([245, 230, 200], dtype=np.float32)
    return out * 0.85 + tint * 0.15 * strength


def binarize(arr, rng, threshold=170, **_):
    g = _gray(arr)
    return np.repeat(np.where(g < threshold, 0.0, 255.0)[..., None], 3, axis=2)


# ── Operators: capture (geometry and lighting) ───────────────────────
def rotation(arr, rng, angle=None, max_angle=3.0, **_):
    a = angle if angle is not None else float(rng.uniform(-max_angle, max_angle))
    img = _to_img(arr)
    fill = tuple(int(c) for c in _paper(arr))
    return _to_np(img.rotate(a, resample=Image.BICUBIC, expand=False, fillcolor=fill)), {"angle": round(a, 2)}


def rotate_quarter(arr, rng, turns=None, **_):
    """Landscape upload: the whole page turned 90 degrees (real uploads include this "sideways.jpg" case)."""
    t = turns if turns is not None else int(rng.choice([1, 3]))
    return np.rot90(arr, t).copy(), {"turns": t}


def _perspective_coeffs(src, dst):
    matrix = []
    for (x, y), (u, v) in zip(dst, src):
        matrix.append([x, y, 1, 0, 0, 0, -u * x, -u * y])
        matrix.append([0, 0, 0, x, y, 1, -v * x, -v * y])
    a = np.array(matrix, dtype=np.float64)
    b = np.array(src, dtype=np.float64).reshape(8)
    return np.linalg.solve(a, b)


def perspective(arr, rng, strength=0.5, oblique=False, **_):
    """Perspective: the four corners pull in randomly. `oblique` is an angled shot (30-45 degrees): one
    side narrows noticeably."""
    h, w = arr.shape[:2]
    m = 0.06 * strength if not oblique else 0.16 * strength
    shifts = rng.uniform(0, m, (4, 2)) * np.array([[w, h]])
    if oblique:
        side = rng.choice([0, 1])
        shifts[[0, 3] if side else [1, 2], 0] *= 0.3   # one side barely moves
    src = [(0, 0), (w, 0), (w, h), (0, h)]
    dst = [(shifts[0, 0], shifts[0, 1]), (w - shifts[1, 0], shifts[1, 1]),
           (w - shifts[2, 0], h - shifts[2, 1]), (shifts[3, 0], h - shifts[3, 1])]
    coeffs = _perspective_coeffs(src, dst)
    fill = tuple(int(c) for c in _paper(arr))
    bg = Image.new("RGB", (w, h), fill)
    warped = _to_img(arr).transform((w, h), Image.PERSPECTIVE, tuple(coeffs), Image.BICUBIC, fillcolor=fill)
    bg.paste(warped)
    # desk/background: darken the area outside the paper, or the perspective wouldn't read
    mask = Image.new("L", (w, h), 0)
    ImageDraw.Draw(mask).polygon([tuple(p) for p in dst], fill=255)
    desk = Image.new("RGB", (w, h), tuple(int(c * rng.uniform(0.35, 0.6)) for c in fill))
    out = Image.composite(bg, desk, mask.filter(ImageFilter.GaussianBlur(1.0)))
    return _to_np(out), {"corners": [[round(float(x), 1), round(float(y), 1)] for x, y in dst]}


def uneven_lighting(arr, rng, strength=0.5, **_):
    h, w = arr.shape[:2]
    angle = rng.uniform(0, 2 * math.pi)
    Y, X = np.mgrid[0:h, 0:w].astype(np.float32)
    g = ((X - w / 2) * math.cos(angle) + (Y - h / 2) * math.sin(angle)) / (max(w, h) / 2)
    g = np.clip(1.0 + g * 0.35 * strength, 0.5, 1.5)
    return arr * g[..., None], {"angle": round(float(angle), 2)}


def vignette(arr, rng, strength=0.5, **_):
    h, w = arr.shape[:2]
    Y, X = np.mgrid[0:h, 0:w].astype(np.float32)
    dist = np.sqrt((X - w / 2) ** 2 + (Y - h / 2) ** 2) / math.hypot(w / 2, h / 2)
    mask = np.clip(1.0 - dist ** 2 * 0.5 * strength, 0.3, 1.0)
    return arr * mask[..., None]


def hand_shadow(arr, rng, strength=0.5, **_):
    """A soft shadow cast by a hand or phone: a dark region reaching in from one edge."""
    h, w = arr.shape[:2]
    mask = Image.new("L", (w, h), 0)
    draw = ImageDraw.Draw(mask)
    edge = rng.choice(["top", "bottom", "left", "right"])
    depth = rng.uniform(0.2, 0.45)
    if edge == "top":
        poly = [(0, 0), (w, 0), (w, h * depth * rng.uniform(0.5, 1)), (0, h * depth)]
    elif edge == "bottom":
        poly = [(0, h), (w, h), (w, h - h * depth * rng.uniform(0.5, 1)), (0, h - h * depth)]
    elif edge == "left":
        poly = [(0, 0), (0, h), (w * depth * rng.uniform(0.5, 1), h), (w * depth, 0)]
    else:
        poly = [(w, 0), (w, h), (w - w * depth * rng.uniform(0.5, 1), h), (w - w * depth, 0)]
    draw.polygon(poly, fill=255)
    m = np.asarray(mask.filter(ImageFilter.GaussianBlur(max(w, h) / 25)), dtype=np.float32) / 255
    return arr * (1 - m * 0.35 * strength)[..., None], {"edge": edge}


def flash_hotspot(arr, rng, strength=0.5, **_):
    """Flash: an overexposed patch above centre, slightly darker towards the edges."""
    h, w = arr.shape[:2]
    cx, cy = w * rng.uniform(0.35, 0.65), h * rng.uniform(0.25, 0.5)
    Y, X = np.mgrid[0:h, 0:w].astype(np.float32)
    r = np.sqrt((X - cx) ** 2 + (Y - cy) ** 2) / (0.35 * max(w, h))
    glare = np.exp(-r ** 2) * 90 * strength
    falloff = np.clip(1.0 - r ** 2 * 0.12 * strength, 0.6, 1.0)
    return arr * falloff[..., None] + glare[..., None]


def cover_glare(arr, rng, strength=0.5, **_):
    """Shot through a plastic sleeve or glass: a diagonal glare band plus an overall drop in contrast."""
    h, w = arr.shape[:2]
    Y, X = np.mgrid[0:h, 0:w].astype(np.float32)
    angle = rng.uniform(0.3, 1.2)
    d = (X * math.cos(angle) + Y * math.sin(angle)) - rng.uniform(0.3, 0.7) * (w * math.cos(angle) + h * math.sin(angle))
    band = np.exp(-(d / (0.06 * max(w, h))) ** 2) * 70 * strength
    out = arr * (1 - 0.12 * strength) + 20 * strength
    return out + band[..., None]


def low_light(arr, rng, strength=0.5, **_):
    return arr * (1 - 0.45 * strength) + rng.normal(0, 6 + 10 * strength, arr.shape).astype(np.float32)


def defocus(arr, rng, strength=0.5, **_):
    return _blur(arr, 0.6 + 1.6 * strength)


def motion_blur(arr, rng, strength=0.5, **_):
    k = max(2, int(2 + 6 * strength))
    angle = rng.uniform(0, math.pi)
    acc = np.zeros_like(arr)
    for i in range(k):
        dx, dy = int(round(i * math.cos(angle))), int(round(i * math.sin(angle)))
        acc += np.roll(np.roll(arr, dy, axis=0), dx, axis=1)
    return acc / k, {"kernel": k, "angle": round(float(angle), 2)}


def sensor_noise(arr, rng, strength=0.5, **_):
    return arr + rng.normal(0, 4 + 14 * strength, arr.shape).astype(np.float32)


def color_temp(arr, rng, shift=None, **_):
    s = shift or rng.choice(["warm", "cool"])
    out = arr.copy()
    if s == "warm":
        out[..., 0] *= 1.08; out[..., 2] *= 0.92
    else:
        out[..., 2] *= 1.08; out[..., 0] *= 0.92
    return out, {"shift": str(s)}


# ── Operators: digital processing ────────────────────────────────────
def resolution_downup(arr, rng, scale=0.5, **_):
    h, w = arr.shape[:2]
    img = _to_img(arr)
    small = img.resize((max(8, int(w * scale)), max(8, int(h * scale))), Image.BOX)
    return _to_np(small.resize((w, h), Image.BILINEAR))


def jpeg_cycle(arr, rng, quality=50, **_):
    buf = io.BytesIO()
    _to_img(arr).save(buf, "JPEG", quality=int(quality))
    return _to_np(Image.open(io.BytesIO(buf.getvalue())))


def downscale(arr, rng, width=1080, **_):
    """Downscale to a phone or chat-app resolution. Resizing operators belong at the end of the chain."""
    h, w = arr.shape[:2]
    if w <= width:
        return arr
    img = _to_img(arr).resize((width, int(h * width / w)), Image.LANCZOS)
    return _to_np(img)


def grayscale(arr, rng, **_):
    return np.repeat(_gray(arr)[..., None], 3, axis=2)


# ── Operators: screen ─────────────────────────────────────────────
def screen_pixels(arr, rng, strength=0.5, **_):
    """A photo of a screen: pixel grid, moire pattern, uneven backlight."""
    h, w = arr.shape[:2]
    Y, X = np.mgrid[0:h, 0:w].astype(np.float32)
    period = rng.uniform(2.6, 3.6)
    grid = 1.0 - 0.18 * strength * ((np.sin(2 * math.pi * X / period) ** 2 + np.sin(2 * math.pi * Y / period) ** 2) / 2)
    f1, f2 = rng.uniform(0.02, 0.05), rng.uniform(0.02, 0.05)
    a1, a2 = rng.uniform(0, math.pi), rng.uniform(0, math.pi)
    moire = 1.0 + 0.10 * strength * np.sin(2 * math.pi * f1 * (X * math.cos(a1) + Y * math.sin(a1))) \
        * np.sin(2 * math.pi * f2 * (X * math.cos(a2) + Y * math.sin(a2)))
    back = 1.0 + 0.12 * strength * np.sin(math.pi * X / w) * np.sin(math.pi * Y / h)
    out = arr * (grid * moire * back)[..., None]
    out[..., 2] *= 1.04                                      # screens skew cool
    return _blur(out, 0.5), {"period": round(float(period), 2)}


def phone_frame(arr, rng, **_):
    """A screenshot: phone status bar, app title bar, bottom nav bar, page scaled to phone width and
    centred. Drawn only with blocks of colour and shapes, no text, so it can't be mistaken for a real
    institution name or timestamp."""
    h, w = arr.shape[:2]
    width = 1080
    scale = width / w
    page = _to_img(arr).resize((width, int(h * scale)), Image.LANCZOS)
    top, bottom = 150, 110
    canvas = Image.new("RGB", (width, page.height + top + bottom), (245, 245, 247))
    draw = ImageDraw.Draw(canvas)
    dark = rng.rand() < 0.3
    bar = (28, 28, 30) if dark else (255, 255, 255)
    fg = (235, 235, 235) if dark else (40, 40, 40)
    draw.rectangle((0, 0, width, top), fill=bar)
    draw.rounded_rectangle((width - 120, 28, width - 60, 56), radius=6, outline=fg, width=3)   # battery
    draw.rectangle((width - 116, 32, width - 116 + int(rng.randint(15, 52)), 52), fill=fg)
    for i in range(4):                                                                        # signal
        draw.rectangle((width - 200 + i * 14, 52 - i * 6, width - 190 + i * 14, 56), fill=fg)
    draw.rounded_rectangle((60, 28, 140, 56), radius=8, fill=fg)                              # clock placeholder
    draw.polygon([(50, 108), (76, 88), (76, 128)], fill=fg)                                   # back arrow
    draw.rounded_rectangle((width // 2 - 140, 96, width // 2 + 140, 120), radius=6, fill=fg)   # title placeholder
    draw.ellipse((width - 90, 96, width - 66, 120), fill=fg)                                   # overflow menu
    canvas.paste(page, (0, top))
    y = top + page.height
    draw.rectangle((0, y, width, y + bottom), fill=bar)
    draw.rounded_rectangle((width // 2 - 130, y + bottom - 24, width // 2 + 130, y + bottom - 14), radius=5, fill=fg)
    return _to_np(canvas), {"dark_mode": bool(dark)}


# ── Operators: added after research (docs/degrade.md §4) ──────────────
def bleed_through(arr, rng, strength=0.3, _next=None, **_):
    """Show-through from double-sided printing: the back page (the next page) mirrored and faintly
    visible (Augraphy BleedThrough / Genalog bleed_through). Check-up books are printed double-sided, so
    scans almost always carry this. Mirrors the current page when there is no next one."""
    src = _next if _next is not None else arr
    if src.shape != arr.shape:
        src = _to_np(_to_img(src).resize((arr.shape[1], arr.shape[0]), Image.BILINEAR))
    flipped = src[:, ::-1]
    g = _gray(flipped)
    mask = _blur(np.repeat(((g < 200) * 255.0)[..., None], 3, axis=2), 2.0)[..., 0] / 255
    return arr - mask[..., None] * 80 * 0.08 * strength / 0.08 * 0.5


def halftone(arr, rng, strength=0.5, cell=4, **_):
    """Ordered dithering (Bayer 4x4): the halftone-dot feel of a photocopy or fax. Blended with the
    original by `strength`, not pure binarization."""
    bayer = np.array([[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]], dtype=np.float32)
    bayer = (bayer + 0.5) / 16 * 255
    h, w = arr.shape[:2]
    tile = np.tile(bayer, (h // 4 + 1, w // 4 + 1))[:h, :w]
    g = _gray(arr)
    dithered = np.where(g > tile, 255.0, 0.0)
    out = np.repeat(dithered[..., None], 3, axis=2)
    a = 0.35 + 0.5 * strength
    return arr * (1 - a) + out * a


def focus_gradient(arr, rng, strength=0.5, **_):
    """Depth of field: sharp on one side, blurred on the other (the far end loses focus in an oblique
    shot; Augraphy DepthSimulatedBlur)."""
    h, w = arr.shape[:2]
    blurred = _blur(arr, 1.0 + 2.5 * strength)
    horizontal = rng.rand() < 0.5
    ramp = (np.linspace(0, 1, w)[None, :] if horizontal else np.linspace(0, 1, h)[:, None]).astype(np.float32)
    if rng.rand() < 0.5:
        ramp = 1 - ramp
    ramp = np.broadcast_to(ramp, (h, w))
    return arr * (1 - ramp[..., None]) + blurred * ramp[..., None], {"horizontal": bool(horizontal)}


def paper_color(arr, rng, tint=None, **_):
    """Coloured paper: lab slips are often printed on pink/yellow/pale-blue carbon-copy or thermal paper
    (Augraphy ColorPaper)."""
    palette = {"pink": (255, 228, 232), "yellow": (255, 246, 214), "blue": (226, 238, 250), "cream": (250, 244, 228)}
    name = tint or ["pink", "yellow", "blue", "cream"][int(rng.randint(0, 4))]
    color = np.array(palette[name], dtype=np.float32) / 255
    return arr * color[None, None, :], {"tint": name}


def finger_occluder(arr, rng, strength=0.5, margin=None, **_):
    """A finger holding down the page edge: drawn only in the page margin, never crossing the content box
    given by `margin`, so ground truth is never touched. `margin` = (left, top, right, bottom) pixels; only
    the area outside that box is allowed."""
    h, w = arr.shape[:2]
    if margin is None:
        return arr
    l, t, r, b = margin
    side = ["left", "right", "bottom"][int(rng.randint(0, 3))]
    if side == "left" and l > 30:
        cx, cy, rx, ry = 0, rng.uniform(0.3, 0.8) * h, min(l - 6, 60 + 40 * strength), 90 + 60 * strength
    elif side == "right" and w - r > 30:
        cx, cy, rx, ry = w, rng.uniform(0.3, 0.8) * h, min(w - r - 6, 60 + 40 * strength), 90 + 60 * strength
    elif side == "bottom" and h - b > 30:
        cx, cy, rx, ry = rng.uniform(0.2, 0.8) * w, h, 70 + 50 * strength, min(h - b - 6, 60 + 40 * strength)
    else:
        return arr
    img = _to_img(arr).convert("RGBA")
    overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    skin = (222, 184, 152, 255) if rng.rand() < 0.7 else (200, 160, 130, 255)
    draw.ellipse((cx - rx, cy - ry, cx + rx, cy + ry), fill=skin)
    shadow = Image.new("RGBA", img.size, (0, 0, 0, 0))
    ImageDraw.Draw(shadow).ellipse((cx - rx - 8, cy - ry + 6, cx + rx + 8, cy + ry + 10), fill=(0, 0, 0, 70))
    shadow = shadow.filter(ImageFilter.GaussianBlur(8))
    img = Image.alpha_composite(img, shadow)
    img = Image.alpha_composite(img, overlay)
    out = _to_np(img.convert("RGB"))
    out[t:b, l:r] = arr[t:b, l:r]          # the shadow's soft edge must not touch the content box either
    return out, {"side": side}


def app_enhance(arr, rng, strength=0.5, **_):
    """A scanning app's "enhance / black-and-white document" mode (CamScanner, WeChat's document scan):
    background forced to white, text darkened and sharpened, leaving grey patches and halos where shadows
    were and slight crop artefacts at the edges. A very common path for real-world uploads."""
    g = _gray(arr)
    # local background estimate (large-kernel blur) -> normalize: shadows lift to white but leave uneven grey patches
    bg = _blur(np.repeat(g[..., None], 3, axis=2), 25)[..., 0]
    norm = np.clip(g / np.maximum(bg, 1) * 245, 0, 255)
    # sharpen: unsharp mask, text gets heavier and blacker
    blurred = _blur(np.repeat(norm[..., None], 3, axis=2), 1.2)[..., 0]
    sharp = np.clip(norm + (norm - blurred) * (1.0 + 1.5 * strength), 0, 255)
    # contrast stretch: close to binary but not quite
    lo, hi = 60 + 60 * strength, 200 - 30 * strength
    out = np.clip((sharp - lo) / max(hi - lo, 1) * 255, 0, 255)
    # leftover halo: a grey band at the old shadow boundary
    halo = np.clip((bg.max() - bg) / 255 * 90 * strength, 0, 60)
    out = np.clip(out - halo * (out > 128), 0, 255)
    return np.repeat(out[..., None], 3, axis=2)


def wechat_scale(arr, rng, long_edge=1280, **_):
    """WeChat's forwarding-compression size rule: unchanged if both sides are <=1280; otherwise the long
    edge is capped at 1280 (when the aspect ratio is <=2)."""
    h, w = arr.shape[:2]
    if max(h, w) <= long_edge:
        return arr
    if max(h, w) / min(h, w) > 2:
        scale = long_edge / min(h, w)           # an extreme long image: cap the short edge at 1280
    else:
        scale = long_edge / max(h, w)
    img = _to_img(arr).resize((max(8, int(w * scale)), max(8, int(h * scale))), Image.LANCZOS)
    return _to_np(img)


def desktop_frame(arr, rng, **_):
    """A desktop browser/reader screenshot: wide canvas, a browser toolbar across the top (colour blocks,
    no text), the page centred with a shadow, grey reader background on both sides. 45% of real images are
    landscape, and this is one of the main reasons why."""
    h, w = arr.shape[:2]
    canvas_w = int(rng.choice([1920, 1680, 1440, 2560]))
    page_w = int(canvas_w * rng.uniform(0.42, 0.6))
    page = _to_img(arr).resize((page_w, int(h * page_w / w)), Image.LANCZOS)
    top = 88
    canvas_h = min(page.height + top + 40, int(canvas_w * 9 / 16) if rng.rand() < 0.5 else page.height + top + 40)
    dark = rng.rand() < 0.35
    bg = (50, 54, 57) if dark else (232, 234, 237)
    canvas = Image.new("RGB", (canvas_w, canvas_h), bg)
    draw = ImageDraw.Draw(canvas)
    bar = (32, 33, 36) if dark else (255, 255, 255)
    fg = (200, 200, 200) if dark else (95, 99, 104)
    draw.rectangle((0, 0, canvas_w, top), fill=bar)
    for i in range(3):                                                             # tabs / window buttons
        draw.ellipse((16 + i * 22, 14, 28 + i * 22, 26), fill=[(255, 95, 86), (255, 189, 46), (39, 201, 63)][i])
    draw.rounded_rectangle((120, 46, canvas_w - 200, 78), radius=8, fill=(241, 243, 244) if not dark else (60, 64, 67))
    draw.rounded_rectangle((140, 56, 140 + int(rng.randint(180, 420)), 68), radius=4, fill=fg)   # address bar
    x = (canvas_w - page_w) // 2
    shadow = Image.new("RGB", (page_w + 16, page.height + 16), tuple(max(0, c - 40) for c in bg))
    canvas.paste(shadow, (x - 8, top + 12))
    canvas.paste(page, (x, top + 8))
    return _to_np(canvas), {"canvas": [canvas_w, canvas_h], "dark": bool(dark)}


# ── Scene table ────────────────────────────────────────────────────
OPS = {
    "paper_texture": paper_texture, "yellowing": yellowing, "fade_ink": fade_ink, "foxing_spots": foxing_spots,
    "stains": stains, "fold_lines": fold_lines, "page_curl": page_curl, "ink_bleed": ink_bleed,
    "toner_banding": toner_banding, "copy_contrast": copy_contrast, "generation_loss": generation_loss,
    "dirty_drum": dirty_drum, "thermal": thermal, "binarize": binarize, "rotation": rotation,
    "rotate_quarter": rotate_quarter, "perspective": perspective, "uneven_lighting": uneven_lighting,
    "vignette": vignette, "hand_shadow": hand_shadow, "flash_hotspot": flash_hotspot, "cover_glare": cover_glare,
    "low_light": low_light, "defocus": defocus, "motion_blur": motion_blur, "sensor_noise": sensor_noise,
    "color_temp": color_temp, "resolution_downup": resolution_downup, "jpeg_cycle": jpeg_cycle,
    "downscale": downscale, "grayscale": grayscale, "screen_pixels": screen_pixels, "phone_frame": phone_frame,
    "bleed_through": bleed_through, "halftone": halftone, "focus_gradient": focus_gradient, "paper_color": paper_color,
    "finger_occluder": finger_occluder, "app_enhance": app_enhance, "wechat_scale": wechat_scale,
    "desktop_frame": desktop_frame,
}
#: Operators needing context: `_next` is the same file's next page (for show-through), `margin` is the
#: content box (a finger may only press outside it).
CONTEXT_OPS = {"bleed_through": "_next", "finger_occluder": "margin"}


def _s(**kw):
    """A parameter sampler: a fixed value, or an (lo, hi) range interpolated by severity."""
    def sample(rng, sev):
        out = {}
        for k, v in kw.items():
            if isinstance(v, tuple) and len(v) == 2 and all(isinstance(x, (int, float)) for x in v):
                lo, hi = v
                val = lo + (hi - lo) * sev
                out[k] = int(round(val)) if isinstance(lo, int) and isinstance(hi, int) else round(float(val), 3)
            else:
                out[k] = v
        return out
    return sample


S = lambda: (lambda rng, sev: {"strength": sev})  # noqa: E731

# T2 scan
_scene("flatbed_scan", "T2", "平板扫描：轻微倾斜、纸纹、双面透印、扫描仪对比度、JPEG", "scanner",
       [("paper_texture", _s(strength=(0.2, 0.5))), ("bleed_through", _s(strength=(0.3, 0.9))),
        ("rotation", _s(max_angle=(0.4, 1.5))), ("copy_contrast", _s(strength=(0.1, 0.3))), ("jpeg_cycle", _s(quality=(95, 80)))])
_scene("app_enhanced", "T2", "扫描 App 增强模式：拍照后自动裁切拉正、背景拉白、文字加黑，残留阴影灰斑", "phone_flat_indoor_normal_top",
       [("perspective", _s(strength=(0.05, 0.15))), ("hand_shadow", _s(strength=(0.4, 0.9))), ("app_enhance", S()),
        ("rotation", _s(max_angle=(0.2, 0.8))), ("downscale", _s(width=1700)), ("jpeg_cycle", _s(quality=(94, 82)))])
_scene("colored_slip", "T2", "有色复写纸/热敏纸上的化验单，扫描或平拍", "scanner",
       [("paper_color", _s()), ("paper_texture", _s(strength=(0.2, 0.4))), ("rotation", _s(max_angle=(0.4, 1.5))),
        ("uneven_lighting", _s(strength=(0.1, 0.4))), ("jpeg_cycle", _s(quality=(94, 80)))])
_scene("scan_lowres", "T2", "低分辨率扫描：150 dpi 级别的模糊 + 强压缩", "scanner",
       [("paper_texture", _s(strength=(0.2, 0.4))), ("rotation", _s(max_angle=(0.5, 2.0))),
        ("resolution_downup", _s(scale=(0.75, 0.5))), ("jpeg_cycle", _s(quality=(75, 45)))])
_scene("scan_grayscale", "T2", "灰度扫描 + 折痕（纸曾对折）", "scanner",
       [("grayscale", _s()), ("fold_lines", _s(strength=(0.4, 0.9), lines=1)), ("rotation", _s(max_angle=(0.3, 1.2))),
        ("copy_contrast", _s(strength=(0.2, 0.5))), ("jpeg_cycle", _s(quality=(85, 65)))])
# T3 phone photo of paper
_scene("phone_flat_top", "T3", "手机俯拍平整纸张，室内正常光", "phone_flat_indoor_normal_top",
       [("perspective", _s(strength=(0.3, 0.8))), ("uneven_lighting", S()), ("vignette", _s(strength=(0.3, 0.7))),
        ("color_temp", _s()), ("defocus", _s(strength=(0.1, 0.5))), ("sensor_noise", _s(strength=(0.2, 0.6))),
        ("downscale", _s(width=2000)), ("jpeg_cycle", _s(quality=(93, 80)))])
_scene("phone_oblique", "T3", "手机斜拍（30–45°），一侧透视收窄、远端失焦", "phone_flat_indoor_normal_oblique",
       [("perspective", _s(strength=(0.5, 1.0), oblique=True)), ("rotation", _s(max_angle=(1.0, 4.0))),
        ("uneven_lighting", S()), ("vignette", _s(strength=(0.3, 0.7))), ("focus_gradient", _s(strength=(0.3, 0.8))),
        ("sensor_noise", _s(strength=(0.2, 0.6))), ("downscale", _s(width=1600)), ("jpeg_cycle", _s(quality=(82, 62)))])
_scene("phone_creased", "T3", "手机俯拍带折痕的纸（从口袋/信封里拿出来的单子），手指压着纸边", "phone_creased_indoor_normal_top",
       [("fold_lines", _s(strength=(0.5, 1.0))), ("finger_occluder", _s(strength=(0.3, 0.8))),
        ("perspective", _s(strength=(0.3, 0.7))), ("uneven_lighting", S()),
        ("hand_shadow", _s(strength=(0.3, 0.8))), ("sensor_noise", _s(strength=(0.2, 0.5))),
        ("downscale", _s(width=1600)), ("jpeg_cycle", _s(quality=(85, 65)))])
_scene("phone_bent", "T3", "手机俯拍弯折未压平的纸", "phone_bent_indoor_normal_top",
       [("page_curl", _s(strength=(0.5, 1.0))), ("perspective", _s(strength=(0.2, 0.6))), ("uneven_lighting", S()),
        ("defocus", _s(strength=(0.2, 0.6))), ("sensor_noise", _s(strength=(0.2, 0.5))),
        ("downscale", _s(width=1600)), ("jpeg_cycle", _s(quality=(85, 65)))])
_scene("phone_lowlight", "T3", "手机俯拍，室内暗光：噪点、抖动模糊、偏暗", "phone_creased_indoor_low_top",
       [("perspective", _s(strength=(0.3, 0.7))), ("low_light", S()), ("motion_blur", _s(strength=(0.3, 0.8))),
        ("vignette", _s(strength=(0.4, 0.8))), ("color_temp", _s(shift="warm")),
        ("downscale", _s(width=1600)), ("jpeg_cycle", _s(quality=(80, 60)))])
_scene("phone_flash", "T3", "手机开闪光灯俯拍：中心过曝", "phone_flat_flash_top",
       [("perspective", _s(strength=(0.3, 0.7))), ("flash_hotspot", S()), ("sensor_noise", _s(strength=(0.1, 0.4))),
        ("downscale", _s(width=1600)), ("jpeg_cycle", _s(quality=(85, 65)))])
_scene("phone_through_cover", "T3", "隔着塑料套/玻璃拍：反光亮带、对比下降", "phone_through_cover_indoor_normal_top",
       [("perspective", _s(strength=(0.3, 0.7))), ("cover_glare", S()), ("uneven_lighting", _s(strength=(0.2, 0.5))),
        ("defocus", _s(strength=(0.1, 0.4))), ("sensor_noise", _s(strength=(0.2, 0.5))),
        ("downscale", _s(width=1600)), ("jpeg_cycle", _s(quality=(85, 65)))])
_scene("phone_landscape", "T3", "整页横放拍摄（真实上传里的『横向.jpg』）", "phone_flat_indoor_normal_top",
       [("perspective", _s(strength=(0.3, 0.7))), ("uneven_lighting", S()), ("rotate_quarter", _s()),
        ("sensor_noise", _s(strength=(0.2, 0.5))), ("downscale", _s(width=1600)), ("jpeg_cycle", _s(quality=(85, 65)))])
# T4 degraded document
_scene("photocopy", "T4", "复印件：对比拉高、灰底、网点、滚筒条纹，再被手机拍下", "phone_photocopy",
       [("grayscale", _s()), ("copy_contrast", _s(strength=(0.3, 0.8))), ("generation_loss", _s(strength=(0.2, 0.6))),
        ("halftone", _s(strength=(0.1, 0.4))), ("dirty_drum", _s(strength=(0.3, 0.8))), ("perspective", _s(strength=(0.2, 0.5))),
        ("uneven_lighting", _s(strength=(0.2, 0.5))), ("downscale", _s(width=1600)), ("jpeg_cycle", _s(quality=(80, 60)))])
_scene("multi_gen_copy", "T4", "多代复印：每复印一次糊一点", "phone_photocopy",
       [("grayscale", _s()), ("copy_contrast", _s(strength=(0.2, 0.5))), ("generation_loss", _s(strength=(0.5, 1.0))),
        ("dirty_drum", _s(strength=(0.3, 0.7))), ("rotation", _s(max_angle=(0.5, 2.5))), ("jpeg_cycle", _s(quality=(75, 55)))])
_scene("fax_thermal", "T4", "传真/热敏打印：近二值、网点、横向条纹、泛黄", "scanner",
       [("thermal", _s(strength=(0.4, 0.9))), ("halftone", _s(strength=(0.2, 0.6))), ("rotation", _s(max_angle=(0.3, 1.5))),
        ("resolution_downup", _s(scale=(0.8, 0.55))), ("jpeg_cycle", _s(quality=(80, 60)))])
_scene("aged_archive", "T4", "泛黄旧档案：纸纹、褪色、霉斑、污渍", "scanner",
       [("paper_texture", S()), ("yellowing", S()), ("fade_ink", S()), ("foxing_spots", S()),
        ("stains", _s(strength=(0.3, 0.7))), ("rotation", _s(max_angle=(0.3, 1.5))), ("jpeg_cycle", _s(quality=(85, 65)))])
_scene("low_quality_print", "T4", "低质量打印：碳粉条带、缺墨条纹，再拍照", "phone_flat_indoor_normal_top",
       [("paper_texture", _s(strength=(0.2, 0.4))), ("toner_banding", S()), ("ink_bleed", _s(strength=(0.2, 0.6))),
        ("perspective", _s(strength=(0.2, 0.5))), ("uneven_lighting", _s(strength=(0.2, 0.5))),
        ("downscale", _s(width=1600)), ("jpeg_cycle", _s(quality=(82, 62)))])
_scene("heavy_compression", "T4", "反复转发：微信长边 1280 规则 + 重度 JPEG 多次重编码", "screenshot_compressed",
       [("wechat_scale", _s(long_edge=1280)), ("jpeg_cycle", _s(quality=(70, 35))), ("resolution_downup", _s(scale=(0.9, 0.6))),
        ("jpeg_cycle", _s(quality=(72, 40)))])
_scene("wechat_photo", "T3", "手机俯拍后经微信转发：长边压到 1280、质量约 75", "phone_flat_indoor_normal_top",
       [("perspective", _s(strength=(0.2, 0.6))), ("uneven_lighting", _s(strength=(0.3, 0.7))), ("hand_shadow", _s(strength=(0.2, 0.6))),
        ("sensor_noise", _s(strength=(0.2, 0.5))), ("wechat_scale", _s(long_edge=1280)), ("jpeg_cycle", _s(quality=(82, 68)))])
# T6 screen
_scene("screen_photo", "T6", "手机拍显示器：像素栅格、摩尔纹、背光", "screen_photography",
       [("screen_pixels", S()), ("perspective", _s(strength=(0.2, 0.6))), ("vignette", _s(strength=(0.3, 0.6))),
        ("sensor_noise", _s(strength=(0.2, 0.5))), ("downscale", _s(width=1600)), ("jpeg_cycle", _s(quality=(82, 62)))])
_scene("screenshot", "T6", "手机长截图（医院 App / 小程序），带状态栏与导航条，转发压缩", "screenshot_compressed",
       [("phone_frame", _s()), ("wechat_scale", _s(long_edge=1280)), ("jpeg_cycle", _s(quality=(78, 50)))])
_scene("desktop_screenshot", "T6", "电脑上打开门户网站 / PDF 阅读器后的截图，横版宽屏，PNG 无损或轻压缩", "screenshot_compressed",
       [("desktop_frame", _s()), ("jpeg_cycle", _s(quality=(95, 80)))])
_scene("clean_photo", "T3", "手机俯拍原图（未经转发）：高质量 JPEG，轻微透视与光照，几乎不糊", "phone_flat_indoor_normal_top",
       [("perspective", _s(strength=(0.1, 0.4))), ("uneven_lighting", _s(strength=(0.2, 0.5))),
        ("sensor_noise", _s(strength=(0.1, 0.3))), ("jpeg_cycle", _s(quality=(96, 90)))])

SEVERITY = {"mild": 0.3, "moderate": 0.6, "severe": 0.9}
TIER_OF_SCENE = {name: s["tier"] for name, s in SCENES.items()}


# ── Entry points ───────────────────────────────────────────────────
def rasterize(pdf_bytes: bytes, dpi: int) -> list[Image.Image]:
    import fitz

    out = []
    with fitz.open("pdf", pdf_bytes) as doc:
        for page in doc:
            pix = page.get_pixmap(dpi=dpi, colorspace=fitz.csRGB, alpha=False)
            out.append(Image.frombytes("RGB", (pix.width, pix.height), pix.samples))
    return out


def content_margins(pdf_bytes: bytes, dpi: int) -> dict[int, tuple[int, int, int, int]]:
    """Each page's text content box, in pixels: (left, top, right, bottom). The page margin outside it is
    where a finger may press."""
    import fitz

    out = {}
    with fitz.open("pdf", pdf_bytes) as doc:
        for i, page in enumerate(doc):
            words = page.get_text("words")
            k = dpi / 72
            if words:
                x0 = min(w[0] for w in words); y0 = min(w[1] for w in words)
                x1 = max(w[2] for w in words); y1 = max(w[3] for w in words)
                out[i] = (int(x0 * k), int(y0 * k), int(x1 * k), int(y1 * k))
    return out


def annotate(pdf_bytes: bytes, seed_text: str, targets: list[str], max_marks: int = 3) -> tuple[bytes, list[str]]:
    """A doctor's or the patient's own pen circling an abnormal value: draws an ellipse around each target
    string on the PDF, never covering the text. Augraphy calls this class Markup/Scribbles; on real
    reports, what gets circled is usually exactly the abnormal item. Returns (new PDF, the circled strings)."""
    import fitz

    rng = np.random.RandomState(int(hashlib.sha1(f"{seed_text}:annotate".encode()).hexdigest()[:8], 16))
    marked: list[str] = []
    with fitz.open("pdf", pdf_bytes) as doc:
        order = list(rng.permutation(len(targets)))
        for idx in order:
            if len(marked) >= max_marks:
                break
            text = targets[idx]
            for page in doc:
                rects = page.search_for(text)
                if rects:
                    r = rects[0]
                    pad = 2.5
                    color = (0.75, 0.1, 0.1) if rng.rand() < 0.6 else (0.1, 0.2, 0.7)
                    shape = page.new_shape()
                    shape.draw_oval(fitz.Rect(r.x0 - pad - 2, r.y0 - pad, r.x1 + pad + 2, r.y1 + pad))
                    shape.finish(color=color, width=0.9 + rng.rand() * 0.6)
                    shape.commit()
                    marked.append(text)
                    break
        return doc.tobytes(garbage=1, deflate=True, no_new_id=True), marked


def apply_scene(pages: list[Image.Image], scene: str, severity: str, seed_text: str,
                content_margins: dict[int, tuple[int, int, int, int]] | None = None
                ) -> tuple[list[Image.Image], list[dict]]:
    """Run the same operator chain on every page (pages from one shoot get similar but not identical
    parameters: the rng carries over from page to page). Returns (page images, per-operator parameter log)."""
    rng = np.random.RandomState(int(hashlib.sha1(f"{seed_text}:{scene}".encode()).hexdigest()[:8], 16))
    sev = SEVERITY[severity]
    log: list[dict] = []
    out_pages = []
    for index, page in enumerate(pages):
        arr = _to_np(page)
        for op_name, sampler in SCENES[scene]["stages"]:
            params = sampler(rng, sev)
            call = dict(params)
            if op_name in CONTEXT_OPS:
                key = CONTEXT_OPS[op_name]
                if key == "_next":
                    call["_next"] = _to_np(pages[index + 1]) if index + 1 < len(pages) else None
                elif key == "margin":
                    call["margin"] = (content_margins or {}).get(index)
            result = OPS[op_name](arr, rng, **call)
            if isinstance(result, tuple):
                arr, extra = result
                params = {**params, **extra}
            else:
                arr = result
            if len(out_pages) == 0:
                log.append({"op": op_name, **params})
        out_pages.append(_to_img(arr))
    return out_pages, log


def encode(pages: list[Image.Image], container: str, doc_title: str) -> bytes:
    """jpg / png: a single page image; scanpdf: a multi-page, text-layer-free image PDF."""
    if container == "jpg":
        exif = Image.Exif()
        exif[0x010E] = SYNTHETIC_MARK          # ImageDescription
        exif[0x0131] = "mirobody-gen"          # Software
        buf = io.BytesIO()
        pages[0].save(buf, "JPEG", quality=92, exif=exif.tobytes())
        return buf.getvalue()
    if container == "png":
        meta = PngImagePlugin.PngInfo()
        meta.add_text("Description", SYNTHETIC_MARK)
        meta.add_text("Software", "mirobody-gen")
        buf = io.BytesIO()
        pages[0].save(buf, "PNG", pnginfo=meta, optimize=True)
        return buf.getvalue()
    if container == "scanpdf":
        import fitz

        pdf = fitz.open()
        for page in pages:
            buf = io.BytesIO()
            page.save(buf, "JPEG", quality=85)
            w, h = page.size
            rect = fitz.Rect(0, 0, w * 72 / 200, h * 72 / 200)
            p = pdf.new_page(width=rect.width, height=rect.height)
            p.insert_image(rect, stream=buf.getvalue())
        pdf.set_metadata({"title": doc_title, "subject": "SYNTHETIC", "keywords": "synthetic; mirobody-gen; scan",
                          "creator": "mirobody-gen", "producer": "mirobody-gen"})
        return pdf.tobytes(garbage=4, deflate=True, no_new_id=True)
    raise ValueError(container)
